Valuable_Again_Team3/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.goods.views import Index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #home page ----- 首页path在这里生成
    path('', Index.as_view(), name='index'),
    path('search', include('haystack.urls')), #full-text retrieval framework
    path('user/', include(('apps.user.urls', 'apps.user'), namespace='user')),
    path('order/', include(('apps.order.urls', 'apps.order'), namespace='order')),
    path('', include(('apps.goods.urls', 'apps.goods'), namespace='goods')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/goods/urls.py
from django.urls import path, include
from apps.goods import views
from apps.goods.views import Index,IndexCategory, AddItem, UpLoadGoodsImage, ItemDetial, Notice

urlpatterns = [
    # path('', views.index, name='index'),
    # path('addItem', views.addItem, name='addItem')
    path('', Index.as_view(), name='index'),
    path('category/<str:category>', IndexCategory.as_view(), name='indexCategory'),
    path('detail/<int:item_id>', ItemDetial.as_view(), name='detail'),
    path('addItem', AddItem.as_view(), name='addItem'),
    path('uploadGoodsImage', UpLoadGoodsImage.as_view(), name='uploadGoodsImage'),
    path('detail/bookGoods', ItemDetial.as_view(), name='bookGoods'),
    path('notice', Notice.as_view(), name='notice'),
    path('user/notice', Notice.as_view(), name='notice'),
    path('detail/notice', Notice.as_view(), name='notice'),
    path('addItem/notice', Notice.as_view(), name='notice'),
    path('category/notice', Notice.as_view(), name='notice'),
]

apps/user/urls.py
from django.urls import path, include

from apps.order.views import CancelOrder, FinishOrder
from apps.user import views
from apps.user.views import RegisterView, LoginView, UserInfoView, \
    UserOrdersView, AddressView,UserItemsView, LogoutView, UpLoadAvatar,SaveAvatar

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),

    path('login/', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),

    path('', UserInfoView.as_view(), name='centerProfile'),
    path('address', AddressView.as_view(), name='centerAddress'),
    path('myItems', UserItemsView.as_view(), name='myItems'),
    path('orders', UserOrdersView.as_view(), name='centerOrders'),
    path('uploadAvatar', UpLoadAvatar.as_view(), name='uploadAvatar'),
    path('saveAvatar', SaveAvatar.as_view(), name='saveAvatar'),
    path('cancel', CancelOrder.as_view(), name='cancelOrder'),
    path('finish', FinishOrder.as_view(), name='finishOrder')
]

apps/goods/models.py
from django.db import models
from db.base_model import BaseModel
from apps.user.models import User

class Items(BaseModel):
    """model of items"""
    user = models.ForeignKey(User, verbose_name='user', on_delete=models.CASCADE)
    itemsName = models.CharField(max_length=32, verbose_name='itemName')
    price = models.FloatField(verbose_name='itemPrice', default=0.0)
    describe = models.CharField(max_length=2000, verbose_name='describe')
    itemCategory = models.CharField(max_length=16, verbose_name='itemCategory')

    #Three status On sale/Booked/Sold
    status = models.CharField(max_length=32, verbose_name='item_status', default="On sale")

    class Meta:
        db_table = "df_items"
        verbose_name = "Items"
        verbose_name_plural=verbose_name

class ItemPicture(BaseModel):
    item = models.ForeignKey(Items, verbose_name='items', on_delete=models.CASCADE)
    itemPicture = models.ImageField(max_length=20, verbose_name='goodsImage', default='default-image.png')

    class Meta:
        db_table = "df_itemPicture"
        verbose_name = "ItemPicture"
        verbose_name_plural = verbose_name

apps/goods/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse, JsonResponse, response
from django.views.generic import View
from tools.mixin import LoginRequiredMixin
from apps.goods.models import Items, ItemPicture
from apps.order.models import Orders
from Valuable_Again_Team3 import settings
import time


class Index(View):
    def get(self, request):
        item = Items.objects.filter(status='On sale').values('itemsName', 'price','id', 'itempicture__itemPicture')
        # item = Items.objects.all().values('itemsName', 'price','id', 'itempicture__itemPicture')
        return render(request, 'goods/index.html', {'items':item})


class IndexCategory(View):
    def get(self, request, category):
        item = Items.objects.filter(itemCategory=category).values('itemsName', 'price', 'id', 'itempicture__itemPicture')
        return render(request, 'goods/index.html', {'items':item})

class ItemDetial(View):
    def get(self, request, item_id):
        item = Items.objects.all().values('itemsName', 'itemCategory', 'price', 'status','id', 'describe','itempicture__itemPicture',
                                          'user__username', 'user__Profile_picture', 'user__address__Address',
                                          'user__email', 'user_id', 'user__address__phone')
        detail = item.get(id=item_id)

        user = request.user


        return render(request, 'goods/detail.html', {'item':detail})

    def post(self, request):
        """set the submit the order"""
        #check the user
        user = request.user
        #
        item_id = request.POST.get("id")

        item = Items.objects.get(id=item_id)
        if item is None:
            return JsonResponse({'success':False, 'errmsg':'No item'})

        itemUser = item.user

        if itemUser == user:
            return JsonResponse({'success':False, 'errmsg':'You cannot buy your own good'})


        #update the data
        item.status = 'Booked'
        item.save()
        Orders.objects.create(seller=itemUser, buyer=user, tradGood=item)

        #update the notice
        itemUser.notices = 'Your good have been booked!'
        itemUser.save()

        return JsonResponse({'success':True})

class AddItem(LoginRequiredMixin,View):
    def get(self, request):
        return render(request, 'goods/addItem.html')

    def post(self, request):
        #receive the data
        user = request.user
        goodsName = request.POST.get('goodsName')
        price = request.POST.get('goodsPrice')
        category = request.POST.get('goodsCategory')
        describe = request.POST.get('goodsDesc')
        image = request.POST.get('goodsImage')

        #check the data
        if not all([goodsName, price, category, describe, image]):
            return JsonResponse({'success': False, 'errmsg': 'Data Missing'})

        #add the data to database
        item = Items.objects.create(user=user,itemsName=goodsName, price=price, describe=describe, itemCategory=category)
        ItemPicture.objects.create(item=item, itemPicture=image)

        return JsonResponse({'success':True})


class UpLoadGoodsImage(LoginRequiredMixin,View):
    def post(self, request):
        # get image file object
        img = request.FILES.get("file", None)

        # get user id
        userId = request.user.id

        # generate a unique file name: avatar-(userID)-(timestamp).(fileType)
        fileEnd = img.name.split('.')[-1]
        fileName = "image-" + str(userId) + '-' + str(int(time.time())) + "." + fileEnd

        save_path = '{}/goodsImages/{}'.format(settings.MEDIA_ROOT, fileName)
        success = False
        with open(save_path, 'wb') as f:
            for content in img.chunks():
                f.write(content)
                success = True

        if success:
            return JsonResponse({'success': True, 'name': fileName})
        else:
            return JsonResponse({'success': False, 'errmsg': "Image upload failed."})

class Notice(LoginRequiredMixin, View):
    def get(self, request):
        #get he notices
        user = request.user
        notice = user.notices
        if notice != None:
            return JsonResponse({'success':True, 'notice':notice})
        else:
            return JsonResponse({'success':False, 'errmsg': 'do not have any notice in database'})

    def post(self, request):
        user = request.user

        #update the notice
        user.notices = 'No any notices'
        user.save()

        return JsonResponse({'success':True})

templates/goods/addItem.html
{% extends 'goods/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add item - Valuable Again
{% endblock %}

{% block head_block %}
    <link href="{% static 'css/add_item.css' %}" rel="stylesheet">
    <script src="{% static 'js/add_item.js' %}"></script>
{% endblock %}

{% block body_block %}
    <div class="main-content container-sm">
        <div class="row">
            <div class="text-center fs-2 fw-light mt-2">Add item</div>
        </div>
        <div class="goods-form-box row p-3">

            <div class="left-box col d-flex flex-column align-items-center">
                <img id="goods-image" src="{% static 'images/default-image.png' %}" class="rounded d-block" width="380" height="280">
                <div id="upload-failed-alert" class="visually-hidden upload-img-alert fs-7 fw-light mx-auto mt-3 alert alert-danger d-flex align-items-center" role="alert">
                    Upload image failed. Please try again
                </div>
                <span id="upload-image-btn" class="btn btn-secondary mt-3">
                    Upload image
                    <input id="upload-image" type="file" accept="image/png, image/jpeg, image/jpg">
                </span>
            </div>

            <div class="right-box col">
                <div class="mb-4 row">
                    <label for="goodsName" class="col-sm-2 col-form-label">Name</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" id="goodsName" name="goodsName" value="">
                    </div>
                </div>
                <div class="mb-4 row">
                    <label for="goodsPrice" class="col-sm-2 col-form-label">Price</label>
                    <div class="col-sm-9">
                        <div class="input-group">
                            <input type="number" class="form-control" id="goodsPrice" name="goodsPrice">
                            <span class="input-group-text">£</span>
                        </div>
                    </div>
                </div>
                <div class="mb-4 row">
                    <label for="goodsPosition" class="col-sm-2 col-form-label">Category</label>
                    <div class="col-sm-9">
                        <select class="form-select" aria-label="Default select example" id="goodsCategory" name="goodsCategory">
                            <option selected>Select a category</option>
                            <option value="Tableware">Tableware</option>
                            <option value="Food">Food</option>
                            <option value="Clothing">Clothing</option>
                            <option value="Device">Device</option>
                            <option value="Furniture">Furniture</option>
                        </select>
                    </div>
                </div>
                <div class="mb-4 row">
                    <label for="goodsDesc" class="col-sm-2 col-form-label">Description</label>
                    <div class="col-sm-9">
                        <textarea type="password" class="form-control" rows="5" id="goodsDesc" name="goodsDesc"></textarea>
                    </div>
                </div>
            </div>

        </div>
        <div class="row p-3">
            <button class="submit-btn btn btn-primary btn-lg mx-auto" onclick="publishItem()">Publish</button>
        </div>
        {{ errmsg }}
    </div>
{% endblock %}

templates/goods/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title_block %}
            Homepage - Valuable Again
        {% endblock %}
    </title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <link href="{% static 'css/goods_base.css'%}" rel="stylesheet">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>
    <script src="{% static 'js/goods_base.js' %}"></script>

    {% block head_block %}

    {% endblock %}
</head>
<body>
<nav id="header" class="navbar navbar-light" style="background-color: #e3f2fd;">
    <div id="header-content" class="container-fluid">
        <a href="{% url 'goods:index' %}">
            <img id="logo-text" src="{% static 'images/logo.png' %}" alt="" width="170" height="40">
        </a>

        <form id="search-form" class="d-flex" role="search" method="get" action="/search">

            <input id="search-input" name="q" class="form-control me-2" type="search" placeholder="Search" aria-label="Search"
                   value="{% block search_query %}{% endblock %}">
            <button class="btn btn-outline-success" type="submit">Search</button>

        </form>
        <div id="right-box" class="d-flex">
            {% if user.is_authenticated %}
                <a id="add-item" type="button" class="btn btn-outline-primary" href="{% url 'goods:addItem' %}">Add item</a>
                <div class="dropdown">
                    <a id="message" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="{% static 'images/message.png' %}" width="40" height="40">
                        {% if user.notices != 'No any notices' %}
                            <div id="message-badge" class="position-relative rounded-circle bg-danger"></div>
                        {% endif %}

                    </a>
                    <div id="notice-box" class="dropdown-menu dropdown-menu-end p-2 fs-6 " aria-labelledby="dropdownMenuButton1">

                        {{ user.notices }}
                        {% if user.notices != 'No any notices' %}
                            <button class="btn btn-sm btn-primary" onclick="noticeChecked()">Got it</button>
                        {% endif %}
                    </div>
                </div>


                <div class="dropdown avatar-box">
                    <a id="user-info" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="{{ MEDIA_URL }}avatars/{{ user.Profile_picture }}" width="40" height="40" class="rounded-circle">
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="user-info">
                        <li><a class="dropdown-item" href="{% url 'goods:index' %}">Home</a></li>
                        <li><a class="dropdown-item" href="{% url 'user:centerProfile' %}">My Profile</a></li>
                        <li><a class="dropdown-item" href="{% url 'user:centerAddress' %}">My Address</a></li>
                        <li><a class="dropdown-item" href="{% url 'user:myItems' %}">My items</a></li>
                        <li><a class="dropdown-item" href="{% url 'user:centerOrders' %}">My orders</a></li>
                        <li><a class="dropdown-item" href="{% url 'user:logout' %}">Logout</a></li>
                    </ul>
                </div>
            {% else %}
                <a id="sign-in" type="button" class="btn" href="{% url 'user:login' %}">Sign in</a>
                <a id="sign-up" type="button" class="btn btn-outline-secondary" href="{% url 'user:register' %}">Sign up</a>
            {% endif %}

        </div>

    </div>

</nav>

{% block body_block %}
{% endblock %}

</body>
</html>

templates/goods/detail.html
{% extends 'goods/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {{ item.itemsName }} - Valuable Again
{% endblock %}

{% block head_block %}
    <link href="{% static 'css/goods_detail.css' %}" rel="stylesheet">
    <script src="{% static 'js/goods_detail.js' %}"></script>
{% endblock %}

{% block body_block %}
    <div class="main-content container-sm">
        <div class="goods-form-box row p-3 border-bottom border-1">

            <div class="left-box col d-flex flex-column align-items-center justify-content-center">
                <img id="goods-image" src="{{ MEDIA_URL }}/goodsImages/{{ item.itempicture__itemPicture }}" class="rounded d-block" width="380" height="280">
            </div>

            <div class="right-box col">
                <div class="mb-3 row">
                    <div class="col-sm-10 fs-1 fw-light">
                        {{ item.itemsName }}
                    </div>
                </div>
                <div class="mb-3 row">
                    <label class="col-sm-2 col-form-label">Category</label>
                    <div class="col-sm-9">
                        <input type="text" readonly disabled class="form-control-plaintext" value="{{ item.itemCategory }}">
                    </div>
                </div>
                <div class="mb-3 row">
                    <label class="col-sm-2 col-form-label">Price</label>
                    <div class="col-sm-9">
                        <div class="input-group fs-3">
                            <input type="text" readonly disabled class="form-control-plaintext item-price" value="£ {{ item.price }}">
                        </div>
                    </div>
                </div>
                <div class="mb-3 row">
                    <label class="col-sm-2 col-form-label">Description</label>
                    <div class="col-sm-9 pt-1">
                        {{ item.describe }}
                    </div>
                </div>
                <div class="mb-3 row">
                    <label class="col-sm-2 col-form-label">Address</label>
                    <div class="col-sm-9">
                        <input type="text" readonly disabled class="form-control-plaintext" value="{{ item.user__address__Address }}">
                    </div>
                </div>
                <div class="mb-3 row">
                    <label class="col-sm-2 col-form-label">Seller</label>
                    <div class="seller-box col-sm-9 d-flex align-items-center">
                        <img src="{{ MEDIA_URL }}/avatars/{{ item.user__Profile_picture }}" class="rounded-circle" width="40" height="40">
                        <div class="m-2">{{ item.user__username }}</div>
                    </div>
                </div>
                <div class="mb-3 row">
                    <label class="col-sm-2 col-form-label">Email</label>
                    <div class="col-sm-9">
                        <input type="text" readonly disabled class="form-control-plaintext" value="{{ item.user__email }}">
                    </div>
                </div>
                {% if item.user__address__phone != '' %}
                    <div class="mb-3 row">
                        <label class="col-sm-2 col-form-label">Phone</label>
                        <div class="col-sm-9">
                            <input type="text" readonly disabled class="form-control-plaintext" value="{{ item.user__address__phone }}">
                        </div>
                    </div>
                {% endif %}
                <div class="mt-4 row">
                    {% if item.status == 'On sale' and user.is_authenticated and user.id != item.user_id%}
                        <button class="book-btn btn btn-success" onclick="bookGoods({{ item.id }})">Book</button>
                    {% elif item.status != 'On sale' %}
                        <label class="col-sm-2 col-form-label">Status</label>
                        <div class="col-sm-9">
                            <span class="fs-6 badge {% if item.status == 'Booked' %}bg-primary{% elif item.status == 'Sold' %}bg-secondary{% endif %}">{{ item.status }}</span>
                        </div>
                    {% endif %}
                </div>
            </div>

        </div>

    </div>
{% endblock %}

templates/goods/index.html
{% extends 'goods/base.html' %}
{% load staticfiles %}

{% block head_block %}
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
    <script src="{% static 'js/index.js' %}"></script>
{% endblock %}

{% block body_block %}
    <div class="main-content container-sm">
        <nav class="category-list nav nav-pills mt-2">
            <a id="category-all" class="nav-link" href="{% url 'goods:index' %}">All</a>
            <a id="category-Tableware" class="nav-link" href="{% url 'goods:indexCategory' 'Tableware' %}">Tableware</a>
            <a id="category-Food" class="nav-link" href="{% url 'goods:indexCategory' 'Food' %}">Food</a>
            <a id="category-Clothing" class="nav-link" href="{% url 'goods:indexCategory' 'Clothing' %}">Clothing</a>
            <a id="category-Device" class="nav-link" href="{% url 'goods:indexCategory' 'Device' %}">Device</a>
            <a id="category-Furniture" class="nav-link" href="{% url 'goods:indexCategory' 'Furniture' %}">Furniture</a>
        </nav>
        <div class="goods-list">
            {% if items %}
                {% for item in items %}
                    <div class=" h-25 goods-card">
                        <div onclick="window.location.href='{% url 'goods:detail' item.id %}'" class="card w-100 h-100 shadow">
                            <img src="{{ MEDIA_URL }}/goodsImages/{{ item.itempicture__itemPicture }}" class="card-img-top">
                            <div class="card-body">
                                <h5 class="card-title">{{ item.itemsName }}</h5>
                            </div>
                            <div class="card-footer">
                                <small class="text-muted">Price: {{ item.price }}</small>
                            </div>
                        </div>

                    </div>
                {% endfor %}
            {% endif %}


        </div>
    </div>
{% endblock %}